export const STATIC_EXECUTION_ROWS = [
  {
    employeeId: 'EMP-1001',
    name: 'Aarav Sharma',
    department: 'Operations',
    weeklyScore: 91,
    trend: 'up',
    trendDelta: 4.8,
    rank: 1,
    rankDelta: 1,
    tasksAssigned: 14,
    tasksCompleted: 13,
    onTimeTasks: 12,
    onTimePercentage: 92,
    consistencyScore: 100,
    qualityScore: 89,
    lastActivityAt: new Date().toISOString(),
    liveScoreDelta: 2.4,
    daily: { Mon: 86, Tue: 88, Wed: 93, Thu: 95, Fri: 92, Sat: 0, Sun: 0 },
    dailyBreakdown: {
      Mon: { date: '2026-03-30', score: 86, tasksAssigned: 3, tasksCompleted: 3, onTimeTasks: 3, onTimePercentage: 100, consistencyScore: 100, qualityScore: 88, hasData: true },
      Tue: { date: '2026-03-31', score: 88, tasksAssigned: 2, tasksCompleted: 2, onTimeTasks: 2, onTimePercentage: 100, consistencyScore: 100, qualityScore: 87, hasData: true },
      Wed: { date: '2026-04-01', score: 93, tasksAssigned: 3, tasksCompleted: 3, onTimeTasks: 2, onTimePercentage: 67, consistencyScore: 100, qualityScore: 92, hasData: true },
      Thu: { date: '2026-04-02', score: 95, tasksAssigned: 3, tasksCompleted: 3, onTimeTasks: 3, onTimePercentage: 100, consistencyScore: 100, qualityScore: 90, hasData: true },
      Fri: { date: '2026-04-03', score: 92, tasksAssigned: 3, tasksCompleted: 2, onTimeTasks: 2, onTimePercentage: 100, consistencyScore: 100, qualityScore: 89, hasData: true },
      Sat: { date: '2026-04-04', score: 0, tasksAssigned: 0, tasksCompleted: 0, onTimeTasks: 0, onTimePercentage: 0, consistencyScore: 0, qualityScore: null, hasData: false },
      Sun: { date: '2026-04-05', score: 0, tasksAssigned: 0, tasksCompleted: 0, onTimeTasks: 0, onTimePercentage: 0, consistencyScore: 0, qualityScore: null, hasData: false },
    },
  },
  {
    employeeId: 'EMP-1002',
    name: 'Priya Nair',
    department: 'Product',
    weeklyScore: 84,
    trend: 'up',
    trendDelta: 1.6,
    rank: 2,
    rankDelta: 0,
    tasksAssigned: 12,
    tasksCompleted: 10,
    onTimeTasks: 9,
    onTimePercentage: 90,
    consistencyScore: 80,
    qualityScore: 93,
    lastActivityAt: new Date(Date.now() - 1000 * 60 * 14).toISOString(),
    liveScoreDelta: 1.2,
    daily: { Mon: 79, Tue: 82, Wed: 0, Thu: 88, Fri: 90, Sat: 0, Sun: 0 },
    dailyBreakdown: {
      Mon: { date: '2026-03-30', score: 79, tasksAssigned: 3, tasksCompleted: 2, onTimeTasks: 2, onTimePercentage: 100, consistencyScore: 100, qualityScore: 90, hasData: true },
      Tue: { date: '2026-03-31', score: 82, tasksAssigned: 2, tasksCompleted: 2, onTimeTasks: 1, onTimePercentage: 50, consistencyScore: 100, qualityScore: 94, hasData: true },
      Wed: { date: '2026-04-01', score: 0, tasksAssigned: 0, tasksCompleted: 0, onTimeTasks: 0, onTimePercentage: 0, consistencyScore: 0, qualityScore: null, hasData: false },
      Thu: { date: '2026-04-02', score: 88, tasksAssigned: 4, tasksCompleted: 3, onTimeTasks: 3, onTimePercentage: 100, consistencyScore: 100, qualityScore: 95, hasData: true },
      Fri: { date: '2026-04-03', score: 90, tasksAssigned: 3, tasksCompleted: 3, onTimeTasks: 3, onTimePercentage: 100, consistencyScore: 100, qualityScore: 93, hasData: true },
      Sat: { date: '2026-04-04', score: 0, tasksAssigned: 0, tasksCompleted: 0, onTimeTasks: 0, onTimePercentage: 0, consistencyScore: 0, qualityScore: null, hasData: false },
      Sun: { date: '2026-04-05', score: 0, tasksAssigned: 0, tasksCompleted: 0, onTimeTasks: 0, onTimePercentage: 0, consistencyScore: 0, qualityScore: null, hasData: false },
    },
  },
  {
    employeeId: 'EMP-1003',
    name: 'Rohan Verma',
    department: 'Operations',
    weeklyScore: 72,
    trend: 'down',
    trendDelta: -3.1,
    rank: 3,
    rankDelta: -1,
    tasksAssigned: 11,
    tasksCompleted: 8,
    onTimeTasks: 6,
    onTimePercentage: 75,
    consistencyScore: 80,
    qualityScore: 81,
    lastActivityAt: new Date(Date.now() - 1000 * 60 * 48).toISOString(),
    liveScoreDelta: -2.3,
    daily: { Mon: 65, Tue: 70, Wed: 74, Thu: 76, Fri: 69, Sat: 0, Sun: 0 },
    dailyBreakdown: {
      Mon: { date: '2026-03-30', score: 65, tasksAssigned: 2, tasksCompleted: 1, onTimeTasks: 1, onTimePercentage: 100, consistencyScore: 100, qualityScore: 80, hasData: true },
      Tue: { date: '2026-03-31', score: 70, tasksAssigned: 2, tasksCompleted: 2, onTimeTasks: 1, onTimePercentage: 50, consistencyScore: 100, qualityScore: 82, hasData: true },
      Wed: { date: '2026-04-01', score: 74, tasksAssigned: 3, tasksCompleted: 2, onTimeTasks: 2, onTimePercentage: 100, consistencyScore: 100, qualityScore: 83, hasData: true },
      Thu: { date: '2026-04-02', score: 76, tasksAssigned: 2, tasksCompleted: 2, onTimeTasks: 1, onTimePercentage: 50, consistencyScore: 100, qualityScore: 79, hasData: true },
      Fri: { date: '2026-04-03', score: 69, tasksAssigned: 2, tasksCompleted: 1, onTimeTasks: 1, onTimePercentage: 100, consistencyScore: 100, qualityScore: 81, hasData: true },
      Sat: { date: '2026-04-04', score: 0, tasksAssigned: 0, tasksCompleted: 0, onTimeTasks: 0, onTimePercentage: 0, consistencyScore: 0, qualityScore: null, hasData: false },
      Sun: { date: '2026-04-05', score: 0, tasksAssigned: 0, tasksCompleted: 0, onTimeTasks: 0, onTimePercentage: 0, consistencyScore: 0, qualityScore: null, hasData: false },
    },
  },
] as const;
