import React from 'react';
import type { SpacesViewController } from '../../hooks/spaces/useSpacesViewController';
import SpacesAiAssignPanel from './SpacesAiAssignPanel';
import SpacesBulkActionsBar from './SpacesBulkActionsBar';
import SpacesMonthGoalsSection from './SpacesMonthGoalsSection';
import SpacesTaskCreateModal from './SpacesTaskCreateModal';
import SpacesTaskModals from './SpacesTaskModals';
import SpacesTaskTableSection from './SpacesTaskTableSection';
import SpacesTaskToolbar from './SpacesTaskToolbar';
import SpacesTopPrioritiesPanel from './SpacesTopPrioritiesPanel';

const SpacesMainSections: React.FC<SpacesViewController> = (props) => {
  const {
    me,
    title,
    setTitle,
    assigneeId,
    setAssigneeId,
    createAssigneeOptions,
    employeesLoading,
    dueDate,
    setDueDate,
    priority,
    setPriority,
    priorityOptions,
    status,
    setStatus,
    emailChecklistEnabled,
    setEmailChecklistEnabled,
    emailChecklistExternalPerson,
    setEmailChecklistExternalPerson,
    externalAssigneeEmail,
    setExternalAssigneeEmail,
    externalAssigneeName,
    setExternalAssigneeName,
    additionalChecklistTitles,
    setAdditionalChecklistTitles,
    reminderIntervalHours,
    setReminderIntervalHours,
    repeatEveryWeek,
    setRepeatEveryWeek,
    repeatCadence,
    setRepeatCadence,
    repeatWeekDays,
    setRepeatWeekDays,
    repeatWeekTime,
    setRepeatWeekTime,
    repeatFromDate,
    setRepeatFromDate,
    repeatToDate,
    setRepeatToDate,
    taskRecurrence,
    setTaskRecurrence,
    statusOptions,
    description,
    setDescription,
    selectedProjectId,
    setSelectedProjectId,
    projectSelectOptions,
    projectsLoading,
    setTaskDocumentFile,
    taskDocumentFile,
    handleCreate,
    saving,
    uploadingTaskDocument,
    error,
    isTaskCreateModalOpen,
    closeTaskCreateModal,
    createTaskPlannerEnabled,
    setCreateTaskPlannerEnabled,
    createTaskPlannerWeekId,
    setCreateTaskPlannerWeekId,
    plannerWeekOptions,
    createTaskPlannerDayId,
    setCreateTaskPlannerDayId,
    plannerDayOptions,
    plannerSummary,
    hideWeeklyPlannerInCreateModal,
    patchTask,
    onCreateMonthGoalTask,
    canPickMonthGoalSchedule,
    canPickMonthGoalAssignee,
    employeeId,
    allowedAssigneeIds,
    assignmentHint,
    monthGoalSaving,
    monthGoalUploading,
    stopTaskRecurrence,
    stoppingRecurrenceTaskId,
    stopTaskEmailChecklist,
    stopTaskWeeklyRepeat,
    deleteTask,
    tasks,
    monthGoalSourceTasks,
    canUseAssigneeFilter,
    taskAssigneeFilterId,
    setTaskAssigneeFilterId,
    taskAssigneeFilterOptions,
    columns,
    isRenamingColumnId,
    renameDraft,
    setRenameDraft,
    setIsRenamingColumnId,
    setActiveColumnMenuId,
    sortedTasks,
    setColumns,
    setError,
    activeColumnMenuId,
    setColumnToDelete,
    handleAddColumn,
    spacesLoading,
    paginatedTasks,
    canEditTask,
    isTaskLocked,
    getTaskRowClasses,
    projectNameById,
    mode,
    assigneeOptionsForTask,
    canEditDueDate,
    canChangeStatus,
    forceDownloadDocument,
    canCommentOnTask,
    setCommentTaskId,
    setModalStatus,
    canValidateTask,
    canDeleteTask,
    handleApproveTask,
    handleRejectTask,
    navigate,
    setEditingTask,
    setEditingTaskMode,
    setEditingTaskDraft,
    setDeleteTaskModal,
    selectedTaskIds,
    canBulkManageTasks,
    toggleTaskSelection,
    canSelectTask,
    taskPage,
    TASKS_PER_PAGE,
    setTaskPage,
    visibleTaskPages,
    totalTaskPages,
    API_BASE,
    getAuthHeaders,
    activeCommentTask,
    setCommentDraft,
    commentDraft,
    editingCommentId,
    setEditingCommentId,
    editCommentDraft,
    setEditCommentDraft,
    setTasks,
    modalStatus,
    handleAddComment,
    submittingComment,
    columnToDelete,
    commentToDeleteId,
    setCommentToDeleteId,
    deleteTaskModal,
    rejectTaskModal,
    rejectFeedbackDraft,
    setRejectFeedbackDraft,
    rejectingTask,
    confirmRejectTask,
    editingTask,
    editingTaskMode,
    editingTaskDraft,
    assignableEmployees,
    bulkAssigneeOptions,
  } = props;

  return (
    <>
      <div className="space-y-4">
        <div className="grid items-stretch gap-4 xl:grid-cols-[minmax(250px,20%)_minmax(0,80%)]">
          <SpacesTopPrioritiesPanel
            topPriorityTasks={props.topPriorityTasks}
            navigate={navigate}
            canChangeStatus={canChangeStatus}
            patchTask={patchTask}
            mode={mode}
          />

          <div className="order-2 flex flex-col rounded-3xl border border-slate-200 bg-white p-5">
            <SpacesMonthGoalsSection
              tasks={monthGoalSourceTasks}
              canUseAssigneeFilter={canUseAssigneeFilter}
              taskAssigneeFilterId={taskAssigneeFilterId}
              setTaskAssigneeFilterId={setTaskAssigneeFilterId}
              taskAssigneeFilterOptions={taskAssigneeFilterOptions}
              patchTask={patchTask}
              onCreateMonthGoalTask={onCreateMonthGoalTask}
              navigate={navigate}
              canEditTask={canEditTask}
              canValidateTask={canValidateTask}
              canPickSchedule={canPickMonthGoalSchedule}
              canPickAssignee={canPickMonthGoalAssignee}
              employeeId={employeeId}
              allowedAssigneeIds={allowedAssigneeIds}
              createAssigneeOptions={createAssigneeOptions}
              employeesLoading={employeesLoading}
              assignmentHint={assignmentHint}
              monthGoalSaving={monthGoalSaving}
              monthGoalUploading={monthGoalUploading}
              setError={setError}
            />
          </div>
        </div>
      </div>

      <SpacesAiAssignPanel
        mode={mode}
        aiAssigning={props.aiAssigning}
        aiAssignFileName={props.aiAssignFileName}
        aiAssignCreatedCount={props.aiAssignCreatedCount}
        aiAssignTotalCount={props.aiAssignTotalCount}
        handleAiAssignPdfUpload={props.handleAiAssignPdfUpload}
      />

      <SpacesTaskToolbar
        setTaskFilterMode={props.setTaskFilterMode}
        taskFilterMode={props.taskFilterMode}
        taskStatusFilter={props.taskStatusFilter}
        taskStatusFilterOptions={props.taskStatusFilterOptions}
        setTaskStatusFilter={props.setTaskStatusFilter}
        taskSearch={props.taskSearch}
        setTaskSearch={props.setTaskSearch}
      />

      <SpacesBulkActionsBar
        canBulkManageTasks={canBulkManageTasks}
        mode={mode}
        selectedTaskCount={props.selectedTaskCount}
        bulkStatus={props.bulkStatus}
        setBulkStatus={props.setBulkStatus}
        bulkTouched={props.bulkTouched}
        setBulkTouched={props.setBulkTouched}
        bulkSaving={props.bulkSaving}
        statusOptions={statusOptions}
        bulkAssigneeId={props.bulkAssigneeId}
        setBulkAssigneeId={props.setBulkAssigneeId}
        employeesLoading={employeesLoading}
        bulkAssigneeOptions={bulkAssigneeOptions}
        bulkDueDate={props.bulkDueDate}
        setBulkDueDate={props.setBulkDueDate}
        clearSelectedTasks={props.clearSelectedTasks}
        saveBulkTaskChanges={props.saveBulkTaskChanges}
        setDeleteTaskModal={setDeleteTaskModal}
        setBulkDeleteTaskModalOpen={props.setBulkDeleteTaskModalOpen}
        bulkReminderIntervalHours={props.bulkReminderIntervalHours}
        setBulkReminderIntervalHours={props.setBulkReminderIntervalHours}
        sendSelectedTaskChecklist={props.sendSelectedTaskChecklist}
        checklistNotice={props.checklistNotice}
      />

      <SpacesTaskTableSection
        columns={columns}
        isRenamingColumnId={isRenamingColumnId}
        renameDraft={renameDraft}
        setRenameDraft={setRenameDraft}
        setIsRenamingColumnId={setIsRenamingColumnId}
        setActiveColumnMenuId={setActiveColumnMenuId}
        sortedTasks={sortedTasks}
        tasks={tasks}
        setColumns={setColumns}
        setError={setError}
        activeColumnMenuId={activeColumnMenuId}
        setColumnToDelete={setColumnToDelete}
        handleAddColumn={handleAddColumn}
        spacesLoading={spacesLoading}
        paginatedTasks={paginatedTasks}
        canEditTask={canEditTask}
        isTaskLocked={isTaskLocked}
        getTaskRowClasses={getTaskRowClasses}
        patchTask={patchTask}
        stopTaskRecurrence={stopTaskRecurrence}
        stopTaskEmailChecklist={stopTaskEmailChecklist}
        stopTaskWeeklyRepeat={stopTaskWeeklyRepeat}
        stoppingRecurrenceTaskId={stoppingRecurrenceTaskId}
        projectNameById={projectNameById}
        mode={mode}
        me={me}
        assigneeOptionsForTask={assigneeOptionsForTask}
        employeesLoading={employeesLoading}
        canEditDueDate={canEditDueDate}
        priorityOptions={priorityOptions}
        canChangeStatus={canChangeStatus}
        statusOptions={statusOptions}
        forceDownloadDocument={forceDownloadDocument}
        canCommentOnTask={canCommentOnTask}
        setCommentTaskId={setCommentTaskId}
        setModalStatus={setModalStatus}
        canValidateTask={canValidateTask}
        canDeleteTask={canDeleteTask}
        handleApproveTask={handleApproveTask}
        handleRejectTask={handleRejectTask}
        navigate={navigate}
        setEditingTask={setEditingTask}
        setEditingTaskMode={setEditingTaskMode}
        setEditingTaskDraft={setEditingTaskDraft}
        setDeleteTaskModal={setDeleteTaskModal}
        setBulkDeleteTaskModalOpen={props.setBulkDeleteTaskModalOpen}
        selectedTaskIds={selectedTaskIds}
        canBulkManageTasks={canBulkManageTasks}
        toggleTaskSelection={toggleTaskSelection}
        canSelectTask={canSelectTask}
        taskPage={taskPage}
        TASKS_PER_PAGE={TASKS_PER_PAGE}
        taskListTotal={props.taskListTotal}
        setTaskPage={setTaskPage}
        visibleTaskPages={visibleTaskPages}
        totalTaskPages={totalTaskPages}
        API_BASE={API_BASE}
        getAuthHeaders={getAuthHeaders}
      />

      <SpacesTaskCreateModal
        open={isTaskCreateModalOpen}
        onClose={closeTaskCreateModal}
        onSubmit={handleCreate}
        canUseEmailChecklist={
          mode === 'manager' ||
          me.role === 'ADMIN' ||
          me.role === 'SUPER_ADMIN' ||
          me.role === 'TEAM_LEAD'
        }
        title={title}
        setTitle={setTitle}
        description={description}
        setDescription={setDescription}
        assigneeId={assigneeId}
        setAssigneeId={setAssigneeId}
        createAssigneeOptions={createAssigneeOptions}
        employeesLoading={employeesLoading}
        dueDate={dueDate}
        setDueDate={setDueDate}
        priority={priority}
        setPriority={setPriority}
        priorityOptions={priorityOptions}
        status={status}
        setStatus={setStatus}
        emailChecklistEnabled={emailChecklistEnabled}
        setEmailChecklistEnabled={setEmailChecklistEnabled}
        emailChecklistExternalPerson={emailChecklistExternalPerson}
        setEmailChecklistExternalPerson={setEmailChecklistExternalPerson}
        externalAssigneeEmail={externalAssigneeEmail}
        setExternalAssigneeEmail={setExternalAssigneeEmail}
        externalAssigneeName={externalAssigneeName}
        setExternalAssigneeName={setExternalAssigneeName}
        additionalChecklistTitles={additionalChecklistTitles}
        setAdditionalChecklistTitles={setAdditionalChecklistTitles}
        reminderIntervalHours={reminderIntervalHours}
        setReminderIntervalHours={setReminderIntervalHours}
        repeatEveryWeek={repeatEveryWeek}
        setRepeatEveryWeek={setRepeatEveryWeek}
        repeatCadence={repeatCadence}
        setRepeatCadence={setRepeatCadence}
        repeatWeekDays={repeatWeekDays}
        setRepeatWeekDays={setRepeatWeekDays}
        repeatWeekTime={repeatWeekTime}
        setRepeatWeekTime={setRepeatWeekTime}
        repeatFromDate={repeatFromDate}
        setRepeatFromDate={setRepeatFromDate}
        repeatToDate={repeatToDate}
        setRepeatToDate={setRepeatToDate}
        taskRecurrence={taskRecurrence}
        setTaskRecurrence={setTaskRecurrence}
        statusOptions={statusOptions}
        selectedProjectId={selectedProjectId}
        setSelectedProjectId={setSelectedProjectId}
        projectSelectOptions={projectSelectOptions}
        projectsLoading={projectsLoading}
        taskDocumentFile={taskDocumentFile}
        setTaskDocumentFile={setTaskDocumentFile}
        saving={saving}
        uploadingTaskDocument={uploadingTaskDocument}
        error={error}
        addToWeeklyPlanner={createTaskPlannerEnabled}
        setAddToWeeklyPlanner={setCreateTaskPlannerEnabled}
        plannerWeekOptions={plannerWeekOptions}
        plannerWeekId={createTaskPlannerWeekId}
        setPlannerWeekId={setCreateTaskPlannerWeekId}
        plannerDayOptions={plannerDayOptions}
        plannerDayId={createTaskPlannerDayId}
        setPlannerDayId={setCreateTaskPlannerDayId}
        plannerSummary={plannerSummary}
        hideWeeklyPlanner={hideWeeklyPlannerInCreateModal}
      />

      <SpacesTaskModals
        activeCommentTask={activeCommentTask}
        setCommentTaskId={setCommentTaskId}
        setCommentDraft={setCommentDraft}
        commentDraft={commentDraft}
        me={me}
        editingCommentId={editingCommentId}
        setEditingCommentId={setEditingCommentId}
        editCommentDraft={editCommentDraft}
        setEditCommentDraft={setEditCommentDraft}
        API_BASE={API_BASE}
        getAuthHeaders={getAuthHeaders}
        setTasks={setTasks}
        setError={setError}
        mode={mode}
        modalStatus={modalStatus}
        setModalStatus={setModalStatus}
        handleAddComment={handleAddComment}
        submittingComment={submittingComment}
        columnToDelete={columnToDelete}
        setColumnToDelete={setColumnToDelete}
        setColumns={setColumns}
        sortedTasks={sortedTasks}
        commentToDeleteId={commentToDeleteId}
        setCommentToDeleteId={setCommentToDeleteId}
        deleteTaskModal={deleteTaskModal}
        setDeleteTaskModal={setDeleteTaskModal}
        bulkDeleteTaskModalOpen={props.bulkDeleteTaskModalOpen}
        setBulkDeleteTaskModalOpen={props.setBulkDeleteTaskModalOpen}
        selectedTaskCount={props.selectedTaskCount}
        bulkSaving={props.bulkSaving}
        deleteSelectedTasks={props.deleteSelectedTasks}
        rejectTaskModal={rejectTaskModal}
        rejectFeedbackDraft={rejectFeedbackDraft}
        setRejectFeedbackDraft={setRejectFeedbackDraft}
        rejectingTask={rejectingTask}
        confirmRejectTask={confirmRejectTask}
        editingTask={editingTask}
        editingTaskMode={editingTaskMode}
        editingTaskDraft={editingTaskDraft}
        setEditingTaskDraft={setEditingTaskDraft}
        assignableEmployees={assignableEmployees}
        forceDownloadDocument={forceDownloadDocument}
        patchTask={patchTask}
        deleteTask={deleteTask}
        setEditingTask={setEditingTask}
        projectSelectOptions={projectSelectOptions}
        projectsLoading={projectsLoading}
        priorityOptions={priorityOptions}
        statusOptions={statusOptions}
        weeklyTaskGroups={props.weeklyTaskGroups}
        getDayDisplay={props.getDayDisplay}
      />
    </>
  );
};

export default SpacesMainSections;
