import type { SpacesTask } from '../../types/spaces';
import { getUserTimeZone } from '../../utils/timezone';

export function getPriorityPillClass(priority?: string) {
  const normalized = String(priority || 'medium').trim().toLowerCase();
  if (normalized === 'high') return 'border border-rose-200 bg-rose-100 text-rose-700';
  if (normalized === 'low') return 'border border-sky-200 bg-sky-100 text-sky-700';
  return 'border border-amber-200 bg-amber-100 text-amber-700';
}

export function getPriorityLabel(priority?: string) {
  const normalized = String(priority || 'medium').trim().toLowerCase();
  if (normalized === 'high') return 'High';
  if (normalized === 'low') return 'Low';
  return 'Medium';
}

export function getAssigneeInitials(name?: string) {
  const parts = String(name || '').trim().split(/\s+/).filter(Boolean);
  if (!parts.length) return 'UN';
  if (parts.length === 1) return parts[0].slice(0, 2).toUpperCase();
  return `${parts[0][0] || ''}${parts[1][0] || ''}`.toUpperCase();
}

export function formatDueDateLabel(value?: string) {
  const raw = String(value || '').trim();
  if (!raw) return '—';
  const [year, month, day] = raw.split('-').map(Number);
  if (!year || !month || !day) return '—';
  const date = new Date(year, month - 1, day);
  return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
}

export function formatOccurrenceDateTimeLabel(value?: string | null) {
  const date = value ? new Date(value) : null;
  if (!date || Number.isNaN(date.getTime())) return '';
  return date.toLocaleString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
    timeZone: getUserTimeZone(),
  });
}

export function isAutoCarriedForwardTask(task?: SpacesTask) {
  return Boolean(task?.autoGenerated && task?.source === 'review_matrix');
}

export function getAutomatedMailSeriesKey(task?: SpacesTask) {
  if (!task) return '';
  if (task.recurrence?.enabled) return task.taskId;
  const parentTaskId = String(task.parentTaskId || task.recurrence?.sourceTaskId || '').trim();
  return parentTaskId || task.taskId;
}

export function taskHasAutomatedMailState(task?: SpacesTask) {
  const checklist = task?.emailChecklist;
  if (!checklist) return false;
  if (checklist.enabled) return true;
  return Boolean(checklist.assignmentSentAt || checklist.lastSentAt || checklist.completedFromEmailAt);
}

export function hasAutomatedMailEnabled(task?: SpacesTask) {
  return Boolean(task?.emailChecklist?.enabled);
}

export function hasStoppedAutomatedMail(task?: SpacesTask) {
  const checklist = task?.emailChecklist;
  if (!checklist || checklist.enabled) return false;
  return Boolean(
    checklist.assignmentSentAt ||
    checklist.lastSentAt ||
    checklist.completedFromEmailAt,
  );
}

export function isUpcomingScheduledMailTask(task?: SpacesTask) {
  const checklist = task?.emailChecklist;
  if (!checklist?.enabled || !checklist.repeatEveryWeek) return false;
  if (checklist.assignmentSentAt || checklist.lastSentAt) return false;
  return Boolean(checklist.nextReminderAt);
}

export function getRepeatingSeriesKey(task?: SpacesTask) {
  if (!task) return '';
  // One series root only: parent/source if present, otherwise this task.
  return String(task.parentTaskId || task.recurrence?.sourceTaskId || task.taskId || '').trim();
}

export function isWeeklyRepeatActive(task?: SpacesTask) {
  const checklist = task?.emailChecklist;
  if (!checklist) return false;
  if (checklist.repeatEveryWeek) return true;
  return Boolean(checklist.enabled && checklist.nextReminderAt);
}

export function isWeeklyRepeatStopped(task?: SpacesTask) {
  const checklist = task?.emailChecklist;
  if (!checklist?.repeatStoppedAt) return false;
  return !isWeeklyRepeatActive(task);
}

export function formatCreatedAtLabel(value?: string) {
  const raw = String(value || '').trim();
  if (!raw) return '';
  const parsed = new Date(raw);
  if (Number.isNaN(parsed.getTime())) return '';
  return parsed.toLocaleString('en-US', {
    month: 'short',
    day: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
    hour12: true,
    timeZone: getUserTimeZone(),
  });
}

export const ROW_MENU_OFFSET = 8;
export const ROW_MENU_FALLBACK_HEIGHT = 192;
export const ROW_MENU_VIEWPORT_PADDING = 12;

export function isRowInteractiveTarget(target: HTMLElement) {
  return Boolean(target.closest('button, select, textarea, input, a, [role="button"]'));
}

export function resolveRowMenuPlacement(
  triggerEl: HTMLButtonElement | null,
  tableCardEl: HTMLDivElement | null,
  menuHeight = ROW_MENU_FALLBACK_HEIGHT,
) {
  if (!triggerEl) return 'bottom' as const;

  const triggerRect = triggerEl.getBoundingClientRect();
  const cardRect = tableCardEl?.getBoundingClientRect();
  const lowerBoundary = Math.min(window.innerHeight - ROW_MENU_VIEWPORT_PADDING, cardRect?.bottom ?? window.innerHeight);
  const upperBoundary = Math.max(ROW_MENU_VIEWPORT_PADDING, cardRect?.top ?? 0);
  const spaceBelow = lowerBoundary - triggerRect.bottom;
  const spaceAbove = triggerRect.top - upperBoundary;

  if (spaceBelow >= menuHeight + ROW_MENU_OFFSET) return 'bottom' as const;
  if (spaceAbove >= menuHeight + ROW_MENU_OFFSET) return 'top' as const;
  return spaceAbove > spaceBelow ? 'top' as const : 'bottom' as const;
}
