import type { Goal, PlanningState } from '../types';

export type SpacesMode = 'employee' | 'manager';
export type BackendRole = 'SUPER_ADMIN' | 'ADMIN' | 'TEAM_LEAD' | 'EMPLOYEE' | string;
export type TaskStatus = 'todo' | 'doing' | 'review' | 'done' | 'blocked';
export type TaskPriority = 'low' | 'medium' | 'high';
export type TaskFilterMode = 'all' | 'me' | 'assigned';
export type CreatePanelTab = 'add-task' | 'top-priorities' | 'weekly-tasks';
export type WeeklyRangeFilter = 'this-week' | 'next-week' | 'two-weeks' | 'month';
export type TaskRecurrenceScheduleMode = 'day' | 'date';
export type TaskCreateRecurrenceFrequency = 'daily' | 'weekly' | 'monthly';
export type TaskCreateRecurrenceEndsType = 'never' | 'on_date' | 'after';

export interface SpacesViewProps {
  mode: SpacesMode;
  state?: PlanningState;
  updateState?: (updater: (prev: PlanningState) => PlanningState) => PlanningState;
}

export interface SelectOption {
  value: string;
  label: string;
}

export interface ProjectOption {
  id: string;
  name: string;
  vision?: string;
}

export interface EmployeeOption {
  empId: string;
  empName: string;
  avatar?: string;
  role?: BackendRole;
}

export interface SpacesColumn {
  id: string;
  name: string;
}

export interface SpacesComment {
  id: string;
  text: string;
  fromEmpId?: string;
  fromName?: string;
  createdAt: string;
  editedAt?: string;
}

export interface SpacesTaskRecurrence {
  enabled?: boolean;
  frequency?: 'secondly' | 'minutely' | 'hourly' | 'daily' | 'weekly' | 'monthly' | '';
  interval?: number;
  maxOccurrences?: number;
  generatedCount?: number;
  nextRunAt?: string | null;
  endDate?: string | null;
  sourceTaskId?: string;
  dayOfWeek?: number | null;
  dayOfMonth?: number | null;
  startMonth?: number | null;
  endMonth?: number | null;
  week_days?: number[];
  month_day?: number | null;
  time?: string;
  ends?: {
    type: TaskCreateRecurrenceEndsType;
    date: string | null;
    occurrences: number | null;
  };
  generatedThrough?: string | null;
}

export interface SpacesTaskEmailChecklist {
  enabled?: boolean;
  reminderIntervalHours?: number;
  assignmentSentAt?: string | null;
  nextReminderAt?: string | null;
  lastSentAt?: string | null;
  completedFromEmailAt?: string | null;
  repeatEveryWeek?: boolean;
  repeatCadence?: 'week' | 'hour' | '2_minutes' | '5_minutes';
  weeklyAnchorAt?: string | null;
  repeatWeekDay?: number | null;
  repeatWeekDays?: number[] | null;
  repeatWeekTime?: string | null;
  repeatFromDate?: string | null;
  repeatToDate?: string | null;
  repeatOccurrences?: number | null;
  remainingOccurrences?: number | null;
  weeklyOccurrenceCompletedAt?: string | null;
  repeatStoppedAt?: string | null;
  occurrenceScheduledAt?: string | null;
}

export interface SpacesTask {
  taskId: string;
  title: string;
  description?: string;
  documentUrl?: string;
  documentName?: string;
  documentMimeType?: string;
  documents?: Array<{
    url: string;
    name: string;
    mimeType?: string;
  }>;
  projectId?: string;
  projectTaskId?: string;
  source?: string;
  autoGenerated?: boolean;
  reviewMatrixId?: string;
  generatedFromDailyReport?: boolean;
  assigneeId?: string;
  assigneeName?: string;
  isViewed?: boolean;
  dueDate?: string;
  priority: TaskPriority;
  status: TaskStatus;
  recurrence?: SpacesTaskRecurrence;
  parentTaskId?: string;
  isRecurring?: boolean;
  emailChecklist?: SpacesTaskEmailChecklist;
  submittedFromStatus?: string;
  comments: SpacesComment[];
  customFields: Record<string, string>;
  createdByEmpId?: string;
  createdByName?: string;
  createdByRole?: BackendRole;
  createdAt: string;
  updatedAt: string;
}

export interface WeeklyTaskGroup {
  week: Goal;
  days: Goal[];
  month?: Goal;
  quarter?: Goal;
  year?: Goal;
  yearId: string;
  quarterId: string;
  monthId: string;
  weekId: string;
  yearLabel: string;
  quarterLabel: string;
  monthLabel: string;
  weekLabel: string;
  quarterNumber: number;
  calendarMonthNumber: number;
  calendarMonthName: string;
  yearWeekNumber: number;
  breadcrumbLabel: string;
  weekRangeLabel: string;
  weekSummaryLabel: string;
  weekStart: Date;
  weekEnd: Date;
  monthIndexInQuarter: number;
  weekIndexInMonth: number;
  isPlaceholderWeek?: boolean;
  weekSelectionKey: string;
}

export interface TaskRecurrenceDraft {
  enabled: boolean;
  scheduleMode: TaskRecurrenceScheduleMode;
  interval: string;
  dayOfWeek: string;
  dayOfMonth: string;
  time: string;
  startMonth: string;
  endMonth: string;
  repeatCount: string;
}

export interface TaskCreateRecurrenceDraft {
  enabled: boolean;
  frequency: TaskCreateRecurrenceFrequency;
  interval: number;
  weekDays: number[];
  monthDay: number;
  time: string;
  ends: {
    type: TaskCreateRecurrenceEndsType;
    date: string | null;
    occurrences: number | null;
  };
}
