import { useMemo, useRef, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { API_BASE, getAuthHeaders } from '../../config/api';
import type { MonthGoalContext } from '../../components/spaces/monthGoalsHelpers';
import type { SpacesViewProps } from '../../types/spaces';
import { forceDownloadDocument, getDayDisplay, getLoggedInEmployee } from '../../views/spacesViewHelpers';
import { useSpacesBootstrap } from './useSpacesBootstrap';
import { useSpacesFilterState } from './useSpacesFilterState';
import { useSpacesFilters } from './useSpacesFilters';
import { useSpacesTasks } from './useSpacesTasks';
import { useSpacesWeeklyPlanner } from './useSpacesWeeklyPlanner';
import { useSpacesModals } from './useSpacesModals';
import { useSpacesTaskCreate } from './useSpacesTaskCreate';
import { useSpacesTaskSubmit } from './useSpacesTaskSubmit';

/**
 * Thin composition root for the Spaces view. Owns only the handful of state
 * values shared across domains (error banner, month-goal create context) and
 * a few refs, then wires together the extracted domain hooks below. The
 * returned object's shape is identical to the original monolithic
 * useSpacesViewController so existing Spaces views keep working unchanged.
 */
export const useSpacesViewController = ({ mode, state, updateState }: SpacesViewProps) => {
  const navigate = useNavigate();
  const location = useLocation();
  const taskHubRootRef = useRef<HTMLDivElement | null>(null);
  const aiAssignRequestIdRef = useRef('');
  const me = useMemo(() => getLoggedInEmployee(), []);
  const [error, setError] = useState<string | null>(null);
  const [createTaskMonthGoalContext, setCreateTaskMonthGoalContext] = useState<MonthGoalContext | null>(null);

  const filters = useSpacesFilterState();

  const bootstrap = useSpacesBootstrap({
    mode,
    state,
    me,
    taskPage: filters.taskPage,
    taskFilterMode: filters.taskFilterMode,
    taskStatusFilter: filters.taskStatusFilter,
    debouncedTaskSearch: filters.debouncedTaskSearch,
    taskAssigneeFilterId: filters.taskAssigneeFilterId,
    setError,
    aiAssignRequestIdRef,
  });

  const views = useSpacesFilters({
    mode,
    me,
    employeeById: bootstrap.employeeById,
    assignableEmployees: bootstrap.assignableEmployees,
    canUseAssigneeFilter: bootstrap.canUseAssigneeFilter,
    tasks: bootstrap.tasks,
    plannerTasks: bootstrap.plannerTasks,
    taskListTotalPages: bootstrap.taskListTotalPages,
    spacesLoading: bootstrap.spacesLoading,
    taskHubRootRef,
    initialTaskFocus: filters.initialTaskFocus,
    taskFilterMode: filters.taskFilterMode,
    setTaskFilterMode: filters.setTaskFilterMode,
    taskAssigneeFilterId: filters.taskAssigneeFilterId,
    setTaskAssigneeFilterId: filters.setTaskAssigneeFilterId,
    taskStatusFilter: filters.taskStatusFilter,
    setTaskStatusFilter: filters.setTaskStatusFilter,
    taskSearch: filters.taskSearch,
    setTaskSearch: filters.setTaskSearch,
    debouncedTaskSearch: filters.debouncedTaskSearch,
    taskPage: filters.taskPage,
    setTaskPage: filters.setTaskPage,
    focusedTaskId: filters.focusedTaskId,
    setFocusedTaskId: filters.setFocusedTaskId,
  });

  const tasksHook = useSpacesTasks({
    mode,
    me,
    tasks: bootstrap.tasks,
    setTasks: bootstrap.setTasks,
    setPlannerTasks: bootstrap.setPlannerTasks,
    employeeById: bootstrap.employeeById,
    updateState,
    taskPage: filters.taskPage,
    loadSpaces: bootstrap.loadSpaces,
    loadPlannerTasks: bootstrap.loadPlannerTasks,
    setError,
    sortedTasks: views.sortedTasks,
    canBulkManageTasks: bootstrap.canBulkManageTasks,
  });

  const weekly = useSpacesWeeklyPlanner({
    state,
    updateState,
    visibleTasks: views.visibleTasks,
    weeklyProjectOptions: bootstrap.weeklyProjectOptions,
    yearlyVisionMetaById: bootstrap.yearlyVisionMetaById,
    createTaskMonthGoalContext,
    canManageWeeklyRows: bootstrap.canManageWeeklyRows,
    canToggleWeeklyDay: bootstrap.canToggleWeeklyDay,
  });

  const modals = useSpacesModals({
    me,
    tasks: bootstrap.tasks,
    assignableEmployees: bootstrap.assignableEmployees,
    employeeById: bootstrap.employeeById,
    canBulkManageTasks: bootstrap.canBulkManageTasks,
    canSelectTask: tasksHook.canSelectTask,
    canChangeStatus: tasksHook.canChangeStatus,
    canEditTask: tasksHook.canEditTask,
    canEditDueDate: tasksHook.canEditDueDate,
    canDeleteTask: tasksHook.canDeleteTask,
    patchTask: tasksHook.patchTask,
    deleteTask: tasksHook.deleteTask,
    loadSpaces: bootstrap.loadSpaces,
    loadPlannerTasks: bootstrap.loadPlannerTasks,
    taskPage: filters.taskPage,
    setError,
  });

  const taskCreate = useSpacesTaskCreate({
    mode,
    me,
    projects: bootstrap.projects,
    appendProjectTaskToState: tasksHook.appendProjectTaskToState,
    navigate,
    location,
    setTasks: bootstrap.setTasks,
    canPickMonthGoalAssignee: bootstrap.canPickMonthGoalAssignee,
    allowedMonthGoalAssigneeIds: bootstrap.allowedMonthGoalAssigneeIds,
    aiAssignRequestIdRef,
    aiAssignProgress: bootstrap.aiAssignProgress,
    setAiAssignProgress: bootstrap.setAiAssignProgress,
    setError,
    setCreateTaskMonthGoalContext,
    weeklyTaskGroups: weekly.weeklyTaskGroups,
    selectedWeeklyTaskGroup: weekly.selectedWeeklyTaskGroup,
    selectedWeeklyDay: weekly.selectedWeeklyDay,
    isNoVisionSelected: weekly.isNoVisionSelected,
    plannerWeekOptions: weekly.plannerWeekOptions,
    setCreateTaskPlannerEnabled: weekly.setCreateTaskPlannerEnabled,
    setCreateTaskPlannerQuarterId: weekly.setCreateTaskPlannerQuarterId,
    setCreateTaskPlannerMonthId: weekly.setCreateTaskPlannerMonthId,
    setCreateTaskPlannerWeekId: weekly.setCreateTaskPlannerWeekId,
    setCreateTaskPlannerDayId: weekly.setCreateTaskPlannerDayId,
  });

  const taskSubmit = useSpacesTaskSubmit({
    me,
    state,
    updateState,
    taskPage: filters.taskPage,
    loadSpaces: bootstrap.loadSpaces,
    setError,
    setChecklistNotice: modals.setChecklistNotice,
    setWeeklyError: weekly.setWeeklyError,
    setSaving: taskCreate.setSaving,
    setUploadingTaskDocument: taskCreate.setUploadingTaskDocument,
    title: taskCreate.title,
    description: taskCreate.description,
    assigneeId: taskCreate.assigneeId,
    dueDate: taskCreate.dueDate,
    priority: taskCreate.priority,
    status: taskCreate.status,
    reminderIntervalHours: taskCreate.reminderIntervalHours,
    selectedProjectId: taskCreate.selectedProjectId,
    taskDocumentFiles: taskCreate.taskDocumentFiles,
    emailChecklistEnabled: taskCreate.emailChecklistEnabled,
    emailChecklistExternalPerson: taskCreate.emailChecklistExternalPerson,
    externalAssigneeEmail: taskCreate.externalAssigneeEmail,
    externalAssigneeName: taskCreate.externalAssigneeName,
    additionalChecklistTitles: taskCreate.additionalChecklistTitles,
    taskRecurrence: taskCreate.taskRecurrence,
    repeatEveryWeek: taskCreate.repeatEveryWeek,
    repeatCadence: taskCreate.repeatCadence,
    repeatWeekDays: taskCreate.repeatWeekDays,
    repeatWeekTime: taskCreate.repeatWeekTime,
    repeatFromDate: taskCreate.repeatFromDate,
    repeatToDate: taskCreate.repeatToDate,
    createTaskMonthGoalContext,
    createTaskPlannerEnabled: weekly.createTaskPlannerEnabled,
    createTaskPlannerWeekId: weekly.createTaskPlannerWeekId,
    createTaskPlannerDayId: weekly.createTaskPlannerDayId,
    activeWeeklyGroups: weekly.activeWeeklyGroups,
    selectedWeeklyTaskGroup: weekly.selectedWeeklyTaskGroup,
    isNoVisionSelected: weekly.isNoVisionSelected,
    uploadTaskDocuments: taskCreate.uploadTaskDocuments,
    buildTaskRecurrencePayload: taskCreate.buildTaskRecurrencePayload,
    createTaskInternal: taskCreate.createTaskInternal,
    closeTaskCreateModal: taskCreate.closeTaskCreateModal,
  });

  const mainSectionsProps = {
    assignmentHint: bootstrap.assignmentHint,
    me,
    title: taskCreate.title,
    setTitle: taskCreate.setTitle,
    assigneeId: taskCreate.assigneeId,
    setAssigneeId: taskCreate.setAssigneeId,
    createAssigneeOptions: bootstrap.createAssigneeOptions,
    employeesLoading: bootstrap.employeesLoading,
    employeeNameById: bootstrap.employeeNameById,
    dueDate: taskCreate.dueDate,
    setDueDate: taskCreate.setDueDate,
    priority: taskCreate.priority,
    setPriority: taskCreate.setPriority,
    priorityOptions: bootstrap.priorityOptions,
    status: taskCreate.status,
    setStatus: taskCreate.setStatus,
    emailChecklistEnabled: taskCreate.emailChecklistEnabled,
    setEmailChecklistEnabled: taskCreate.setEmailChecklistEnabled,
    emailChecklistExternalPerson: taskCreate.emailChecklistExternalPerson,
    setEmailChecklistExternalPerson: taskCreate.setEmailChecklistExternalPerson,
    externalAssigneeEmail: taskCreate.externalAssigneeEmail,
    setExternalAssigneeEmail: taskCreate.setExternalAssigneeEmail,
    externalAssigneeName: taskCreate.externalAssigneeName,
    setExternalAssigneeName: taskCreate.setExternalAssigneeName,
    additionalChecklistTitles: taskCreate.additionalChecklistTitles,
    setAdditionalChecklistTitles: taskCreate.setAdditionalChecklistTitles,
    reminderIntervalHours: taskCreate.reminderIntervalHours,
    setReminderIntervalHours: taskCreate.setReminderIntervalHours,
    repeatEveryWeek: taskCreate.repeatEveryWeek,
    setRepeatEveryWeek: taskCreate.setRepeatEveryWeek,
    repeatCadence: taskCreate.repeatCadence,
    setRepeatCadence: taskCreate.setRepeatCadence,
    repeatWeekDays: taskCreate.repeatWeekDays,
    setRepeatWeekDays: taskCreate.setRepeatWeekDays,
    repeatWeekTime: taskCreate.repeatWeekTime,
    setRepeatWeekTime: taskCreate.setRepeatWeekTime,
    repeatFromDate: taskCreate.repeatFromDate,
    setRepeatFromDate: taskCreate.setRepeatFromDate,
    repeatToDate: taskCreate.repeatToDate,
    setRepeatToDate: taskCreate.setRepeatToDate,
    taskRecurrence: taskCreate.taskRecurrence,
    setTaskRecurrence: taskCreate.setTaskRecurrence,
    statusOptions: bootstrap.statusOptions,
    description: taskCreate.description,
    setDescription: taskCreate.setDescription,
    selectedProjectId: taskCreate.selectedProjectId,
    setSelectedProjectId: taskCreate.setSelectedProjectId,
    projectSelectOptions: bootstrap.projectSelectOptions,
    projectsLoading: bootstrap.projectsLoading,
    setTaskDocumentFiles: taskCreate.setTaskDocumentFiles,
    taskDocumentFiles: taskCreate.taskDocumentFiles,
    handleCreate: taskSubmit.handleCreate,
    saving: taskCreate.saving,
    uploadingTaskDocument: taskCreate.uploadingTaskDocument,
    aiAssigning: taskCreate.aiAssigning,
    aiAssignFileName: taskCreate.aiAssignFileName,
    aiAssignCreatedCount: taskCreate.aiAssignProgress?.created || 0,
    aiAssignTotalCount: taskCreate.aiAssignProgress?.total || 0,
    handleAiAssignPdfUpload: taskCreate.handleAiAssignPdfUpload,
    error,
    isTaskCreateModalOpen: taskCreate.isTaskCreateModalOpen,
    openTaskCreateModal: taskCreate.openTaskCreateModal,
    closeTaskCreateModal: taskCreate.closeTaskCreateModal,
    createTaskPlannerEnabled: weekly.createTaskPlannerEnabled,
    setCreateTaskPlannerEnabled: weekly.setCreateTaskPlannerEnabled,
    createTaskPlannerWeekId: weekly.createTaskPlannerWeekId,
    setCreateTaskPlannerWeekId: weekly.setCreateTaskPlannerWeekId,
    plannerWeekOptions: weekly.plannerWeekOptions,
    createTaskPlannerDayId: weekly.createTaskPlannerDayId,
    setCreateTaskPlannerDayId: weekly.setCreateTaskPlannerDayId,
    plannerDayOptions: weekly.plannerDayOptions,
    plannerSummary: weekly.plannerSummary,
    hideWeeklyPlannerInCreateModal: Boolean(createTaskMonthGoalContext),
    topPriorityTasks: views.topPriorityTasks,
    patchTask: tasksHook.patchTask,
    onCreateMonthGoalTask: taskCreate.createMonthGoalTask,
    canPickMonthGoalSchedule: bootstrap.canPickMonthGoalSchedule,
    canPickMonthGoalAssignee: bootstrap.canPickMonthGoalAssignee,
    employeeId: me.id || '',
    allowedAssigneeIds: bootstrap.allowedMonthGoalAssigneeIds,
    monthGoalSaving: taskCreate.monthGoalSaving,
    monthGoalUploading: taskCreate.uploadingTaskDocument,
    stopTaskRecurrence: tasksHook.stopTaskRecurrence,
    stopTaskEmailChecklist: tasksHook.stopTaskEmailChecklist,
    stopTaskWeeklyRepeat: tasksHook.stopTaskWeeklyRepeat,
    stoppingRecurrenceTaskId: tasksHook.stoppingRecurrenceTaskId,
    deleteTask: tasksHook.deleteTask,
    weeklyError: weekly.weeklyError,
    state,
    updateState,
    selectedWeeklyDay: weekly.selectedWeeklyDay,
    selectedWeeklyTaskGroup: weekly.selectedWeeklyTaskGroup,
    weeklyTaskGroups: weekly.weeklyTaskGroups,
    weeklyPeriodPicker: weekly.weeklyPeriodPicker,
    getWeekBreadcrumb: weekly.getWeekBreadcrumbForView,
    getWeekStartDate: weekly.getWeekStartDateForView,
    getDayDisplay,
    setSelectedDayByWeek: weekly.setSelectedDayByWeek,
    tasks: bootstrap.tasks,
    monthGoalSourceTasks: views.monthGoalSourceTasks,
    canUseAssigneeFilter: bootstrap.canUseAssigneeFilter,
    taskAssigneeFilterId: filters.taskAssigneeFilterId,
    setTaskAssigneeFilterId: filters.setTaskAssigneeFilterId,
    taskAssigneeFilterOptions: views.taskAssigneeFilterOptions,
    toggleDaily: weekly.toggleDaily,
    canManageWeeklyRows: bootstrap.canManageWeeklyRows,
    canToggleWeeklyDay: bootstrap.canToggleWeeklyDay,
    createDaysForWeek: weekly.createDaysForWeek,
    setTaskFilterMode: filters.setTaskFilterMode,
    taskFilterMode: filters.taskFilterMode,
    taskStatusFilter: filters.taskStatusFilter,
    taskStatusFilterOptions: bootstrap.taskStatusFilterOptions,
    setTaskStatusFilter: filters.setTaskStatusFilter,
    taskSearch: filters.taskSearch,
    setTaskSearch: filters.setTaskSearch,
    columns: bootstrap.columns,
    isRenamingColumnId: modals.isRenamingColumnId,
    renameDraft: modals.renameDraft,
    setRenameDraft: modals.setRenameDraft,
    setIsRenamingColumnId: modals.setIsRenamingColumnId,
    setActiveColumnMenuId: modals.setActiveColumnMenuId,
    sortedTasks: views.sortedTasks,
    setColumns: bootstrap.setColumns,
    setError,
    activeColumnMenuId: modals.activeColumnMenuId,
    setColumnToDelete: modals.setColumnToDelete,
    handleAddColumn: bootstrap.handleAddColumn,
    spacesLoading: bootstrap.spacesLoading,
    paginatedTasks: views.paginatedTasks,
    canEditTask: tasksHook.canEditTask,
    isTaskLocked: tasksHook.isTaskLocked,
    getTaskRowClasses: tasksHook.getTaskRowClasses,
    projectNameById: bootstrap.projectNameById,
    mode,
    assigneeOptionsForTask: bootstrap.assigneeOptionsForTask,
    canEditDueDate: tasksHook.canEditDueDate,
    canChangeStatus: tasksHook.canChangeStatus,
    forceDownloadDocument,
    canCommentOnTask: tasksHook.canCommentOnTask,
    setCommentTaskId: tasksHook.setCommentTaskId,
    setModalStatus: tasksHook.setModalStatus,
    canValidateTask: tasksHook.canValidateTask,
    canDeleteTask: tasksHook.canDeleteTask,
    handleApproveTask: tasksHook.handleApproveTask,
    handleRejectTask: tasksHook.handleRejectTask,
    navigate,
    setEditingTask: modals.setEditingTask,
    setEditingTaskMode: modals.setEditingTaskMode,
    setEditingTaskDraft: modals.setEditingTaskDraft,
    setDeleteTaskModal: modals.setDeleteTaskModal,
    selectedTaskIds: modals.selectedTaskIds,
    selectedTaskCount: modals.selectedTasks.length,
    canBulkManageTasks: bootstrap.canBulkManageTasks,
    bulkSaving: modals.bulkSaving,
    bulkReminderIntervalHours: modals.bulkReminderIntervalHours,
    setBulkReminderIntervalHours: modals.setBulkReminderIntervalHours,
    checklistNotice: modals.checklistNotice,
    sendSelectedTaskChecklist: modals.sendSelectedTaskChecklist,
    bulkStatus: modals.bulkStatus,
    setBulkStatus: modals.setBulkStatus,
    bulkAssigneeId: modals.bulkAssigneeId,
    setBulkAssigneeId: modals.setBulkAssigneeId,
    bulkDueDate: modals.bulkDueDate,
    setBulkDueDate: modals.setBulkDueDate,
    bulkTouched: modals.bulkTouched,
    setBulkTouched: modals.setBulkTouched,
    toggleTaskSelection: modals.toggleTaskSelection,
    clearSelectedTasks: modals.clearSelectedTasks,
    saveBulkTaskChanges: modals.saveBulkTaskChanges,
    bulkDeleteTaskModalOpen: modals.bulkDeleteTaskModalOpen,
    setBulkDeleteTaskModalOpen: modals.setBulkDeleteTaskModalOpen,
    deleteSelectedTasks: modals.deleteSelectedTasks,
    canSelectTask: tasksHook.canSelectTask,
    taskPage: filters.taskPage,
    TASKS_PER_PAGE: views.TASKS_PER_PAGE,
    taskListTotal: bootstrap.taskListTotal,
    setTaskPage: filters.setTaskPage,
    visibleTaskPages: views.visibleTaskPages,
    totalTaskPages: views.totalTaskPages,
    focusedTaskId: filters.focusedTaskId,
    API_BASE,
    getAuthHeaders,
    activeCommentTask: tasksHook.activeCommentTask,
    setCommentDraft: tasksHook.setCommentDraft,
    commentDraft: tasksHook.commentDraft,
    editingCommentId: tasksHook.editingCommentId,
    setEditingCommentId: tasksHook.setEditingCommentId,
    editCommentDraft: tasksHook.editCommentDraft,
    setEditCommentDraft: tasksHook.setEditCommentDraft,
    setTasks: bootstrap.setTasks,
    modalStatus: tasksHook.modalStatus,
    handleAddComment: tasksHook.handleAddComment,
    submittingComment: tasksHook.submittingComment,
    columnToDelete: modals.columnToDelete,
    commentToDeleteId: tasksHook.commentToDeleteId,
    setCommentToDeleteId: tasksHook.setCommentToDeleteId,
    deleteTaskModal: modals.deleteTaskModal,
    rejectTaskModal: tasksHook.rejectTaskModal,
    setRejectTaskModal: tasksHook.setRejectTaskModal,
    rejectFeedbackDraft: tasksHook.rejectFeedbackDraft,
    setRejectFeedbackDraft: tasksHook.setRejectFeedbackDraft,
    rejectingTask: tasksHook.rejectingTask,
    confirmRejectTask: tasksHook.confirmRejectTask,
    editingTask: modals.editingTask,
    editingTaskMode: modals.editingTaskMode,
    editingTaskDraft: modals.editingTaskDraft,
    assignableEmployees: bootstrap.assignableEmployees,
    bulkAssigneeOptions: modals.bulkAssigneeOptions,
  };

  return {
    taskHubRootRef,
    ...mainSectionsProps,
  };
};

export type SpacesViewController = ReturnType<typeof useSpacesViewController>;
